name: 🕶️

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  style-checks:
    name: Run style checks
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - uses: actions/checkout@v4
      - run: python3 -m pip install -r requirements.txt
      - run: |
          python3 -m pip install flake8
          python3 -m flake8 .
        name: Run flake8 checks
